---
- name: Hello World!
  hosts: all
 
  tasks:
 
  - name: Hello World!
    shell: echo "Hi! Tower is working. "
    register: hello

- name: Debug hello
  - debug: msg="{{ hello.stdout }}"

- name: Debug hello
  - debug: msg="{{ hello.stderr }}"
