---
- hosts: 172.21.0.1:5001
  connection: local

  tasks:
    - name: Show VLAN
      ios_command:
        commands: show vlan brief
      register: show_vlan

    - debug: var=show_vlan.stdout_lines
